expression ::= equality
primary ::= NUMBER | STRING | "true" | "false" | "nil" | "(" expression ")"
unary ::= ( "!" | "-" ) unary
unary ::= ( "!" | "-" ) unary | primary
factor ::= factor ( "/" | "*" ) unary | unary
factor ::= unary ( ( "/" | "*" ) unary )*